name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install pngquant
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install -r mkdocs/requirements.txt
      - run: mkdocs gh-deploy --config-file mkdocs/mkdocs.yml --force
      - name: Add CNAME
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages
          echo "partners.fontlab.com" > CNAME
          git add CNAME
          git commit -m "Add CNAME"
          git push origin gh-pages
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
